### ISSUE TITLE
Example calculating crc32c from file?

### ISSUE THREAD

**Issue by vsoch** [ICRAR/crc32c#14]
I'm looking for an example to calculate the has directly from a file - I'm hoping it's something similar to hashlib where you can stream chunks and update a hasher object. I looked at the testing file, but it looks like there are only tests for byte strings defined directly there. My goal is to be able to validate downloads from Google Storage based on this checksum, since they are provided with the objects. Thanks in advance for your help!

**Comment by vsoch** [comment]
I also just found http://crcmod.sourceforge.net/intro.html#installation which is linked from the [Google page](https://cloud.google.com/storage/docs/hashes-etags) - this looks like it has matching functions to update, etc. Does this library implement crc32c or just crc32?

**Comment by rtobar** [comment]
This package allows you to accumulate the result of the hashing as you iterate over a stream of data. You'll need to read chunks of data off your file and feed them into `crc32c.crc33` in a loop, passing down the previous checksum value as well. Basically like in the tests, but reading data chunks from your file.

Do yes, no explicit hasher object, but still can be done. This design was based on that from the built-in `binascii.crc32` so they are easily interchangeable.

**Comment by vsoch** [comment]
Thank you! I'll follow up after some testing tomorrow and then close the issue.

**Comment by vsoch** [comment]
I'm just curious - why is it called crc32c if the module is import as crc32? The two algorithms are different, and it's confusing if I have the right one.

Since the google storage client doesn't implement streaming to file (and I want to stream just once when writing) I implemented a supporting class:

```python
class Crc32cCalculator(object):
    """The Google Python client doesn't provide a way to stream a file being
       written, so we can wrap the file object in an additional class to
       do custom handling. This is so we don't need to download the file
       and then stream read it again to calculate the hash.
   """
    def __init__(self, fileobj):
        self._fileobj = fileobj
        self.digest = 0 

    def write(self, chunk):
        self._fileobj.write(chunk)
        self._update(chunk)

    def _update(self, chunk):
        """Given a chunk from the read in file, update the hexdigest
        """
        self.digest = crc32(chunk, self.digest)

    def hexdigest(self):
        """Return the hexdigest of the hasher
        """
        return self.digest
```

and then use as follows:

```python
with open(self.local_file(), "wb") as blob_file:
        parser = Crc32cCalculator(blob_file)
        self.blob.download_to_file(parser)
```
And then I would want to compare. But the units seem to be different - is there a final conversion to/from bytes or hex I need to do?

```python
>>> self.blob.crc32c
'nuFtcw=='
>>> parser.hexdigest()
2665573747
```

**Comment by rtobar** [comment]
> I'm just curious - why is it called crc32c if the module is import as crc32? The two algorithms are different, and it's confusing if I have the right one.

Agreed, this could be improved. The package in PyPI is called `crc32c`, and the module is called `crc32c`, but it exposes a function called `crc32`. To be honest this is probably historical baggage -- when this package was first implemented it tried to mimic `binascii.crc32` to an extreme, including the function name... Maybe in a later release we could adjust the name

>  is there a final conversion to/from bytes or hex I need to do?

I don't know what `self.blob.crc32c` here represents, so it's a bit difficult to understand how to convert backwards and forwards. It looks like a base64 encoding, but that's as much as I can say about it. If you have some more documentation regarding how they get that value it would be possible to confirm they are the same (or not!).

**Comment by vsoch** [comment]
The docs here: https://cloud.google.com/storage/docs/hashes-etags say:

> The Base64 encoded CRC32c is in big-endian byte order

Maybe that is what we need?

**Comment by rtobar** [comment]
```python
import base64
import struct
print(base64.b64encode(struct.pack('>I', 2665573747)))
````

**Comment by vsoch** [comment]
Woo success! I almost got there (https://stackoverflow.com/questions/846038/convert-a-python-int-into-a-big-endian-string-of-bytes/12859903) but missed the base64 import and encoding. Thank you so kindly! I’m going to finish up my class and I’ll post here for future people to see.

**Comment by vsoch** [comment]
okay, here is the final result (extracted from a class)!

```python
import os
import base64
import struct
from crc32c import crc32
import google.cloud
from google.cloud import storage
```

I made the crc32c calculator to wrap the file object for blob.download_to_file, and add a function to update the hasher with each chunk. The last bit of our discussion to compute the matching value for the blob is now added here:

```python
class Crc32cCalculator(object):
    """The Google Python client doesn't provide a way to stream a file being
       written, so we can wrap the file object in an additional class to
       do custom handling. This is so we don't need to download the file
       and then stream read it again to calculate the hash.
   """

    def __init__(self, fileobj):
        self._fileobj = fileobj
        self.digest = 0

    def write(self, chunk):
        self._fileobj.write(chunk)
        self._update(chunk)

    def _update(self, chunk):
        """Given a chunk from the read in file, update the hexdigest
        """
        self.digest = crc32(chunk, self.digest)

    def hexdigest(self):
        """Return the hexdigest of the hasher.
           The Base64 encoded CRC32c is in big-endian byte order.
           See https://cloud.google.com/storage/docs/hashes-etags
        """
        return base64.b64encode(struct.pack(">I", self.digest)).decode("utf-8")
```

And then for the download() function of a remote object class, if the blob exists, we loop until it's correct. Below, self refers to a remote object class. self.local_file() can be essentially viewed as a string. Note that we instantiate the parser shown above when we open the file to write, that way we can provide the file object to the class above at the same time as we are opening the file to write. I didn't want to write the file to the system, and then stream it again to read for the hasher.

```python
    def download(self):
        if not self.exists():
            return None

        # Create the directory for the intended file
        os.makedirs(os.path.dirname(self.local_file()), exist_ok=True)

        # Continue trying to download until hash matches
        while not os.path.exists(self.local_file()):

            # ideally we could calculate hash while streaming to file with provided function
            # https://github.com/googleapis/python-storage/issues/29
            with open(self.local_file(), "wb") as blob_file:
                parser = Crc32cCalculator(blob_file)
                self.blob.download_to_file(parser)
            os.sync()

            # Compute local hash and verify correct
            if parser.hexdigest() != self.blob.crc32c:
                os.remove(self.local_file())

        return self.local_file()
```

Likely we should add a max number of retries or other ways to catch some unexpected error, but I'm starting with this as the most basic example for review.

Thank you so kindly for all of your help! This was very fun to work with you to figure out, and I hope will be useful for someone in the future. Closing issue.
