### ISSUE TITLE
CRC32 calculation correct?

### ISSUE THREAD

**Issue by marco74** [ICRAR/crc32c#23]
When comparing to other algorithms the result differs. Am I doing anything wrong?

```python
>>> import crc32c
>>> import zlib
>>> zlib.crc32(b'\x01\x02\x03')
1438416925
>>> crc32c.crc32c(b'\x01\x02\x03')
4046516766
```

**Comment by rtobar** [comment]
@marco74 yes, that's expected. `zlib` computes the CRC-32, while this package computes CRC-32C. The algorithm is the same, but the starting polynomial is different. For details see https://en.wikipedia.org/wiki/Cyclic_redundancy_check#Polynomial_representations_of_cyclic_redundancy_checks

**Comment by marco74** [comment]
@rtobar Thank you for the clarification.
