### ISSUE TITLE
Add support to release aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [ICRAR/crc32c#25]
Problem
---------
On aarch64, ‘pip install crc32c’ builds the wheels from source code and then installs it. It requires the user to have a development environment installed on his system. Also, it takes some time to build the wheels than downloading and extracting the wheels from pypi.

Resolution
-----------
On aarch64, ‘pip install crc32c’ should download the wheels from pypi

@rtobar Please let me know your interest in releasing aarch64 wheels. I can help with this.

**Comment by rtobar** [comment]
Thanks for the suggestion and the PR, this is now on the latest `master` and a new PyPI release is being produced.
