### ISSUE TITLE
Python 3.10 Wheels?

### ISSUE THREAD

**Issue by william-silversmith** [ICRAR/crc32c#28]
Hi, 

Thanks for this great project! I've been having some trouble installing a dependent package with Python 3.10. It's possible this is an Apple Silicon issue. This works fine for py38 and py39. I think what is happening is compiling the wheel dies if I'm installing packages using a Rosetta2 terminal as it gets confused regarding arm vs x86 headers. If I compile in an ARM64 terminal it works.

If a wheel were available, my Rosetta2 terminal would download it and either run it as arm or translate it from x86 to arm.

Thanks so much for reading.

**Comment by rtobar** [comment]
@william-silversmith thanks for opening this issue, and sorry for the late reply.

Do you have a copy of the error that occurs when building the wheel under Rosetta2? It's an interesting scenario, and one I don't have experience with; I'd assume that under Rosetta2 the python interpreter would report being run under x86_64, so the package would be compiled in that mode, but that's a guess.

Regarding wheels, python 3.10 wasn't out when the latest version on this package was released, hence the missing wheels. I'll see if I can trigger the CI pipeline to build new ones for 3.10. If that's possible then I'll upload them to PyPI.

**Comment by william-silversmith** [comment]
Thanks for the reply!

Here's the error: 
```
$ pip install crc32c --no-cache-dir

Collecting crc32c
  Downloading crc32c-2.2.post0.tar.gz (38 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: crc32c
  Building wheel for crc32c (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [34 lines of output]
      running bdist_wheel
      running build
      running build_ext
      platform: x86_64, is_intel: 1, is_arm: 0
      building 'crc32c' extension
      creating build
      creating build/temp.macosx-10.9-universal2-3.10
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -DNDEBUG -DIS_INTEL -I. -I/Users/USER/.virtualenvs/kimi310/include -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c _crc32c.c -o build/temp.macosx-10.9-universal2-3.10/_crc32c.o -O3 -msse4.2 -mpclmul
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -DNDEBUG -DIS_INTEL -I. -I/Users/USER/.virtualenvs/kimi310/include -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c checkarm.c -o build/temp.macosx-10.9-universal2-3.10/checkarm.o -O3 -msse4.2 -mpclmul
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -DNDEBUG -DIS_INTEL -I. -I/Users/USER/.virtualenvs/kimi310/include -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c checksse42.c -o build/temp.macosx-10.9-universal2-3.10/checksse42.o -O3 -msse4.2 -mpclmul
      In file included from checksse42.c:39:
      /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.0.0/include/cpuid.h:14:2: error: this header is for x86 only
      #error this header is for x86 only
       ^
      /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.0.0/include/cpuid.h:286:5: error: invalid output constraint '=a' in asm
          __cpuid(__leaf, __eax, __ebx, __ecx, __edx);
          ^
      /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.0.0/include/cpuid.h:251:11: note: expanded from macro '__cpuid'
              : "=a"(__eax), "=r" (__ebx), "=c"(__ecx), "=d"(__edx) \
                ^
      /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.0.0/include/cpuid.h:301:5: error: invalid output constraint '=a' in asm
          __cpuid(__leaf, *__eax, *__ebx, *__ecx, *__edx);
          ^
      /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.0.0/include/cpuid.h:251:11: note: expanded from macro '__cpuid'
              : "=a"(__eax), "=r" (__ebx), "=c"(__ecx), "=d"(__edx) \
                ^
      /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.0.0/include/cpuid.h:315:5: error: invalid output constraint '=a' in asm
          __cpuid_count(__leaf, __subleaf, *__eax, *__ebx, *__ecx, *__edx);
          ^
      /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.0.0/include/cpuid.h:258:11: note: expanded from macro '__cpuid_count'
              : "=a"(__eax), "=r" (__ebx), "=c"(__ecx), "=d"(__edx) \
                ^
      4 errors generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for crc32c
  Running setup.py clean for crc32c
Failed to build crc32c
```

**Comment by rtobar** [comment]
@william-silversmith thanks again for the further details, and sorry again for the delay in my response. I was away from work and returned only very recently, so now I've been able to give this a bit more of attention.

Thanks to your log above I was able to determine this problem was a mix of platform detection (we didn't account for the `universal2` platform in our code), and the fact that in this platform a single compilation pass compiles the code twice for the different architectures. Our build system was not prepared for this, and thus it failed to build properly for this dual-arch target platform.

Based on this I've fixed the issues and have been able to build of `universal2` wheels with our cibuildwheel-based CI. Could you give them a try? You can get the wheels from the `artifact.zip` file produced by the [latest build of the support-universal2-builds branch](https://github.com/ICRAR/crc32c/actions/runs/2205336564). At the bottom of the page you can download the "artifact.zip" file, and inside you'll find all the wheels generated for all systems. Select the macos universal2 binary wheel that corresponds to your python version and give it a go. I don't have an M1 Mac at hand, but at least I can see that the compiled extension from the python 3.10 universal2 mac binary wheel has two architectures in them:

```
$> file crc32c.cpython-310-darwin.so 
crc32c.cpython-310-darwin.so: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit x86_64 bundle, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL>] [arm64:Mach-O 64-bit arm64 bundle, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL>]
```

I'm curious to see in particular firstly if it works, and secondly if you get the hardware acceleration that should be expected from ARmv8 chips.

**Comment by william-silversmith** [comment]
Hi rtobar,

Thanks for your response and fix! I downloaded it and the wheel loaded fine in a py3.10 environment. I ran a simple test on 10MB of data 10x:

```python
import random
import string
import crc32c
import time

def random_string_generator(str_size, allowed_chars):
    return (''.join(random.choice(allowed_chars) for x in range(str_size))).encode('utf8')
 
chars = string.ascii_letters + string.punctuation

data = random_string_generator(10**7, chars)

s = time.time()
for i in range(10):
    x = crc32c.crc32c(data)
print(time.time() - s)
print(x)
```

This executed in 5 msec, so it seems like the acceleration is there. Blistering fast!

**Comment by rtobar** [comment]
@william-silversmith good news to hear :). Could you do one more test for me and print what `crc32c.hardware_based` gives you? I'm also curious to see what performance you get from executing with and without rosetta2 (if possible, no pressure!)

After this I'll be doing a minor version release which should put all the new wheels up in PyPI for easy public consumption.

**Comment by william-silversmith** [comment]
I get `True` on `arch i386` (Rosetta2) and `False` for `arch arm64` even if I make a new virutalenv on an arm terminal and install it again. The test above was run on i386. On arm, it seems the same test is still pretty fast (!) but 10x slower. It took 55 msec.

**Comment by rtobar** [comment]
Thanks @william-silversmith for the further testing. I think you got what I was expecting: binary wheels in macOS arm64 will work, but only on software mode. Enabling hw acceleration for those is a task for a different day.

I've now merged the changes to the `master` branch, so the next version of crc32c on PyPI should have binary wheels for all macOS architectures: `x86_64`, `arm64` and `universal2`.
