### ISSUE TITLE
The package is wrongly forcing `-msse4.2 -mpclmul` on all x86 systems

### ISSUE THREAD

**Issue by mgorny** [ICRAR/crc32c#30]
The following code:

https://github.com/ICRAR/crc32c/blob/3812a8e2cbdd7d257d074783e0c0aa178e3629bd/setup.py#L63-L65
https://github.com/ICRAR/crc32c/blob/3812a8e2cbdd7d257d074783e0c0aa178e3629bd/setup.py#L42-L43

is unconditionally appending `-msse4.2 -mpclmul` on all x86 systems. This means that the compiler can optimize *any* code to use these instructions, and therefore cause the package to crash on a system without it.

To correctly use SSE4.2 runtime detection, you need to append these flags *only* for files that use them, and make sure that none of the functions declared in them are called before SSE4.2 is successfully detected.

Alternatively, you could mark the functions with something like:
```c
__attribute__((target("sse4.2")))
```
https://github.com/llvm/llvm-project/blob/20434bf3731389773fb8569889bd5d06375683bf/clang/test/CodeGen/attr-target-crc32-x86.c#L31-L33

But I suppose it's less portable.

**Comment by rtobar** [comment]
@mgorny thanks for the report. In principle you're right, but have you seen any issue in practice with this? That would provide a better estimate of the urgency to take care of this.

**Comment by mgorny** [comment]
No, I haven't — but I don't have old hardware handy, nor time to set up VMs for this. However, this is sufficient to block inclusion into Gentoo.

**Comment by rtobar** [comment]
Ok, thanks for that further info, I'll try to have a look at this sooner than later then.

**Comment by mgorny** [comment]
I could try preparing a PR, if you'd like. I'd use `__attribute__` when compiler is GCC, and ideally remove the whole `/O2`/`-O3` business, as packages shouldn't override user flags anyway.

**Comment by rtobar** [comment]
Sure, happy to go along with a PR in that direction
