### ISSUE TITLE
Compiling to a WebAssembly target

### ISSUE THREAD

**Issue by agriyakhetarpal** [ICRAR/crc32c#39]
Hi there! I am trying to package, in specific, add a recipe for `crc32c` for [Pyodide](https://pyodide.org/), a Python distribution compiled using the [Emscripten toolchain](https://emscripten.org/) to [WebAssembly](https://webassembly.org/) that enables running Python code [in the browser](https://blog.pyodide.org/). I thought that I should reach out here! Would a package maintainer or core developer for `crc32c` be able to help out on the compilation side of things? I imagine that with the help of the maintainers and author(s) here, this arduous task would be rendered much easier than with the efforts of a limited number of people who would otherwise be trying to figure this out alone.

I would be happy to share further context around this: the reason for this feature request is that [version 3](https://github.com/zarr-developers/zarr-python/pull/1583) of the [Zarr](https://zarr.dev/) Python package is going to use `crc32c` as a [required dependency](https://github.com/zarr-developers/zarr-python/pull/1903), and therefore wheels for `crc32c` for a `wasm32` platform tag (with the ABI and ABI tags managed by the Emscripten version), which would be distributed through the [Pyodide CDN](https://www.jsdelivr.com/package/npm/pyodide) [across browsers](https://pyodide.org/en/stable/usage/index.html#supported-browsers) and handled by Pyodide's infrastructure and developer tooling for [building in-tree packages](https://pyodide.org/en/stable/development/new-packages.html) would be a wonderful addition towards bringing Zarr (and other dependents that might be using `crc32c`) to run on WASM-based platforms like [JupyterLite](https://jupyterlite.readthedocs.io/).

<hr>

xref: here is the corresponding issue on the Pyodide repository that I opened a while ago: https://github.com/pyodide/pyodide/issues/4787

**Comment by agriyakhetarpal** [comment]
I raised https://github.com/pyodide/pyodide#4789 and I think the recipe seems to build without issues with the Emscripten toolchain – I'm now waiting for the tests to run (and hopefully pass). Would one of the maintainers have sufficient bandwidth and like to be listed as a maintainer for the recipe as well, besides me?

**Comment by agriyakhetarpal** [comment]
I raised pyodide/pyodide#4789 and I think the recipe seems to build without issues with the Emscripten toolchain – I'm now waiting for the tests to run (and hopefully pass). Would one of the maintainers have sufficient bandwidth and like to be listed as a maintainer for the recipe as well, besides me?

**Comment by rtobar** [comment]
Many thanks @agriyakhetarpal for reaching out, and for the excellent overview of the context within which this sits.

I had a cursory look at the PRd and associated documents/files/etc, and whether with what you mentioned above it seems like the package is already compiling as expected? I saw some failures in some of the CI jobs in  https://github.com/pyodide/pyodide/pull/4789, but I'm not familiar with the overall state of that pipeline; in a words, are those failures expected?

In terms of commitment, I can fully commit to enhance this package in any way it's required to compile in wasm platforms. OTOH I'd be hesitant to add myself as a maintainer of the pyodide recipe at this stage, since I'm 100% not familiar with their build process. I'm in a long period of leave ATM, but I might be able to play with it a bit, and maybe I'd gain some confidence. And again, changes to this package I'm more than happy to support.

Finally, as it turns out, we ourselves will probably end up using zarr in the near future in our of our projects, so it's nice this is coming back all the way.

**Comment by agriyakhetarpal** [comment]
Thank you for the warm response, @rtobar! Yes, the package is already compiling as expected and some of the CI jobs, quoting the words of the core Pyodide developers, are a bit flaky at some time or the other and therefore are known failures, even if they are expected ones or not. I think I just need to fix the `crc32c`-specific test cases there, which should be doable, and we should be good to go then.

> In terms of commitment, I can fully commit to enhance this package in any way it's required to compile in wasm platforms. OTOH I'd be hesitant to add myself as a maintainer of the pyodide recipe at this stage, since I'm 100% not familiar with their build process. I'm in a long period of leave ATM, but I might be able to play with it a bit, and maybe I'd gain some confidence. And again, changes to this package I'm more than happy to support.

I understand your uncertainty about not wishing to be a maintainer for the Pyodide recipe, no worries about it – I can act as the _de facto_ maintainer in that regard. The blog posts and the documentation are, IMO, excellent resources to read up on if you would wish to know more.

One way that `crc32c` would benefit would be if an out-of-tree Pyodide CI job could be added to this repository – this job would then install Pyodide, Emscripten, Node.js, and the necessary runtime dependencies, and then run the already existing test suite on PR builds or at a cadence you like, which would render Pyodide a semi-supported platform for this package for current versions and advances to later ones (as long as the CI job keeps passing).

I would be happy to set that up for you and maintain it for a few iterations of the bi-annual Pyodide releases as you see fit, please let me know! That said, it could also be overkill, though, since we are going to be using a subset of the test suite for the in-tree job, and given the size of the package, it might not be needed in essence. Indeed, Zarr is wonderful and to keep supporting it for WebAssembly would be great – getting `crc32c` in would mean we are halfway there (the rest of the required dependencies except one are already available)!

**Comment by agriyakhetarpal** [comment]
Successfully merged! `crc32c` should now be available as in-tree in the upcoming Pyodide 0.26.0, corresponding to Emscripten 3.1.58 and Python 3.12.1.
