### ISSUE TITLE
Intentional fallthrough?

### ISSUE THREAD

**Issue by r-barnes** [ICRAR/crc32c#46]
Is this fallthrough intentional? The code currently does not compile with `-Wimplicit-fallthrough` enabled.

If the fallthrough is intentional, can it be marked with `__attribute__((fallthrough))`? If not, can we add `break` to fix the bug? 

https://github.com/ICRAR/crc32c/blob/dd5d18ad0d2ba3ffd84bb77650b70ee9d5d09e51/crc32c_adler.c#L235

(There are actually _many_ implicit fallthroughs - compiling with the `-Wimplicit-fallthrough` flag and driving that value to zero has, in my experience, a high chance of identifying bugs.)

**Comment by rtobar** [comment]
Thanks @r-barnes for pointing this out. I didn't write all of the C codes that are part of the package, so I'll need to go through each of these; however my feeling is that they are all valid.

I looked at the one in particular that you linked above, and reading the code indeed gave me the impression it was OK. It depends on memory alignment though, and we don't have tests that ensure we traverse all those paths, so I've added one now (to be merged). The new test passes with the code as-is, and fails if I add the `break`, as expected.

I'll keep updating here once I'm done with all the fallthroughs. And yes, I'll add the necessary annotations, that's always a good idea.

**Comment by rtobar** [comment]
OK, I've now gone through all implicit fallthroughs and annotated them as necessary. I've also added a new test that hits the code paths that were previously missing, thus confirming the current behaviour is correct (see c8ce4650f0908b8d9d7bf7986f0eae1bf7cae2d5).

Changes pushed to `master`, hence closing this issue now.

Thanks again @r-barnes for reporting this!
