### ISSUE TITLE
class “crc32c.CRC32CHash” seems doesn't pass parameter "gil_release_mode" to crc32c.crc32c()

### ISSUE THREAD

**Issue by ssh-buanshishi** [ICRAR/crc32c#51]
I have seen the lastest commit about class “CRC32CHash”: https://github.com/ICRAR/crc32c/commit/ad65e59a2f12f89aec191a299391a46efd03917a

Source code from line 39 to 51:
`    def __init__(self, data: Buffer = b"") -> None:
        """
        Initialise the hash object with an optional bytes-like object.
        """
        self._checksum = crc32c(data)

    def update(self, data: Buffer) -> None:
        """
        Update the hash object with the bytes-like object.
        Repeated calls are equivalent to a single call with the concatenation of all the arguments:
        m.update(a); m.update(b) is equivalent to m.update(a+b).
        """
        self._checksum = crc32c(data, self._checksum)`

In the code shown above, parameter "gil_release_mode" is not mentioned.
My instincts tells me that: Parameter "gil_release_mode" may be not passed to "crc32c()", so it's not suppoted by class “CRC32CHash”.

I tried to use "crc32c.CRC32CHash(b"Initail Bytes" , gil_release_mode=1)" and "crc32c_hash=crc32c.CRC32CHash() ; crc32c_hash.update(b'hello' , gil_release_mode=1)" in Python IDLE later, and got " TypeError:  __init__() / update() got an unexpected keyword argument 'gil_release_mode' ", this guess seems to be more right now.

If my way of usage was wrong, then I'm sorry to interrupt your work. 
If my guess is confirmed later, I hope the source code will be improved, since the core function "crc32c.crc32c()" supports this parameter formerly, but after class “CRC32CHash” be introduced in this module, this parameter became useless again in some ways.

I am from China, my English expression may not be good.
Finally, thanks for watching.

**Comment by rtobar** [comment]
@ssh-buanshishi thanks for getting in touch. `CRC32CHash` is a new addition to the library, and I'm happy to hear feedback already coming for it :+1: 

Yes, indeed the option is not supported by `CRC32CHash`, I think due to a mixture of us forgetting about it, and because the package's default behaviour is convenient, releasing the GIL only when it pays off. However, I see your point that this introduces an asymmetry in the API, and it takes very little effort to fix that. I'll add it to `CRC32CHash.__init__`, it makes more sense to specify it only once per hash object rather than on each call to `update`.

**Comment by ssh-buanshishi** [comment]
>  I'll add it to CRC32CHash.__init__, it makes more sense to specify it only once per hash object rather than on each call to update.

Thanks for the reply, and I couldn't agree more about the specific idea and method mentioned above.👌

**Comment by ssh-buanshishi** [comment]
Oh,  by the way, I have a little advice about the manual shown to users on homepage.

You can add:
> crc32c_hash = crc32c.CRC32CHash(b'hello')
crc32c_hash.update(b' world')
print(crc32c_hash._checksum , type(crc32c_hash._checksum))
# 3381945770 <class 'int'>

Especially the last two lines, it can tell users that use "._checksum" method can get the originally interger hash result from class "crc32c.CRC32CHash()".

**Comment by rtobar** [comment]
@ssh-buanshishi thanks for the suggestion. I wouldn't want to encourage users to access members that are not supposed to be public though, so I'll add something different that still shows how the `digest` is the same as what would calculate via the `crc32c` function.

**Comment by rtobar** [comment]
@ssh-buanshishi I've now merged to `master` the addition of the `gil_release_mode` flag to the `CRC32CHash.__init__` function, where it's kept around and used throughout all the underlying `crc32c` computations. Thanks again for the suggetsion!

**Comment by ssh-buanshishi** [comment]
The reason I raised this "._checksum" suggestion is all for my own convenience from my perspective.
You can say I'm a "lazy" guy in some ways. "The digest is the same as what would calculate via the crc32c function", that's true, but after reading the convertion method "int.from_bytes(crc32c_hash.digest(), "big")", emmm…… , maybe "._checksum" is still more convenient for me, since this method needs no convertion and consideration about "big-endian" and "little-endian" at all.

I understand this non-public method could be a little "dangerous" when using it, so I respect your decision to not show it to public. I will use "._checksum" with caution and notice source code changes in this parameter, thank you for your explanation.

Finally, thank you for the enthusiastic replies throughout the talk.
If there are any useful suggestions later, I'll be very glad to submit them here.

**Comment by rtobar** [comment]
@ssh-buanshishi it didn't occur to me when you first proposed the changes to the `README` file, but now I've added a new `CRC32C.checksum` property (publicly visible, it simply returns the underluing `_checksum` value) that returns the "raw" checksum as calculated by ``crc32c`.

**Comment by ssh-buanshishi** [comment]
Thank you very much. It's really a surprise that my wish become true now. I wasn't expecting much from this.

I thought you can easily get my point about the benefits(needs no convertion) on adding "._checksum"(now is ".checksum") when you saw my suggestion at first, but it turned out to be the opposite in the end🤣🤣🤣.

Emmm..., well, that's my fault, I should have made my point clear at first😅.
