### ISSUE TITLE
Building on non-Intel platforms

### ISSUE THREAD

**Issue by jlaine** [ICRAR/crc32c#6]
First of all thanks for making this package available! I'm making use of this package in `aiortc`, a Python implementation of WebRTC, as the SCTP layer uses crc32c checksums. The performance with SSE instructions is amazing, but what's more even the software implementation is faster that `crcmod`.

It was recently brought to my attention that attempting to build the package on non-Intel platforms fails, due to the SSE-specific compiler flags (https://github.com/jlaine/aiortc/issues/119), so I've had to add a fallback to `crcmod`.

Given that you already have a plain C implementation, how hard would it be to adjust the build system to skip the SSE version altogether on non-Intel platfoms?

**Comment by rtobar** [comment]
Hi @jlaine,

Thanks for dropping by, it's always good to see that this package is being used.

In principle this should not be too difficult to do. In the past the code was already architecture-aware, but with time we assumed an Intel architecture for simplicity (hence the hardcorded flags in `setup.py`). Luckily I own a Raspberry Pi, so I'll use this as a test platform and make sure the module compiles correctly there. Once this is done I'll release a new version to PyPI and will let you know here about it.
